sudo: required
services: 
  - docker

before_install:
  - docker build -t dhmlau/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dhmlau/docker-react npm run test -- --coverage

before_deploy: 
#  - curl -L https://clis.ng.bluemix.net/download/bluemix-cli/0.6.1/linux64 | tar -zx
  - curl -sL https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/linux-installer/idt-installer | bash
#  - chmod -R u+x ./Bluemix_CLI/bin
  - chmod +x ./deploy.sh

deploy:
  - provider: script
    script: ./deploy.sh
    on:
      branch: master
    skip_cleanup: true